spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:h2:mem:mylog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  session:
    timeout: 86400
jiheon:
  jwt-key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaavaaaaaaaaaaaaaaaaaa"
  
server:
  servlet:
    session:
      cookie:
        max-age: 172800
