### 테스트 요쳥

## 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "jiheon",
  "email": "aaaa@aaaa.com",
  "password": "aaaa@aaaa.com"
}

### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username = aaaa@aaaa.com &
password = aaaa@aaaa.com

### 메인 페이지
GET http://localhost:8080


### 사용자 페이지
GET http://localhost:8080/user

### 관리자 페이지
GET http://localhost:8080/admin
