### 테스트 요쳥

POST http://localhost:8080/auth/login
Content-Type:  application/x-www-form-urlencoded

username = jiheon &
password = 2234

### 인증페이지 요청
GET http://localhost:8080/foo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.oDEEvrJfB9OKZx_SeWcpB7RJ2Geu4-HFcVqUTHwAO6g